version: '3.7'

services:
  zoo1-m:
    image: zookeeper:3.7.0
    restart: always
    hostname: zoo1-m
    container_name: zoo1-m
    ports:
      - 2182:2182
    environment:
        ZOO_MY_ID: 1
        ZOO_PORT: 2182
        ZOO_SERVERS: server.1=zoo1-m:2888:3888;2182
    volumes:
      - ./zk/zoo1-m/data:/data
      - ./zk/zoo1-m/datalog:/datalog

  kafka1-m:
    image: confluentinc/cp-kafka:6.2.0
    hostname: kafka1-m
    container_name: kafka1-m
    ports:
      - "9292:9292"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1-m:19292,LISTENER_DOCKER_EXTERNAL://localhost:9292
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1-m:2182"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: kafka1-m
    volumes:
      - ./zk/kafka1-m/data:/var/lib/kafka/data
    depends_on:
      - zoo1-m

  zoo1:
    image: zookeeper:3.7.0
    restart: always
    hostname: zoo1
    container_name: zoo1
    ports:
      - 2181:2181
    environment:
        ZOO_MY_ID: 1
        ZOO_PORT: 2181
        ZOO_SERVERS: server.1=zoo1:2888:3888;2181
    volumes:
      - ./zk/zoo1/data:/data
      - ./zk/zoo1/datalog:/datalog

  kafka1:
    image: confluentinc/cp-kafka:6.2.0
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: kafka1
    volumes:
      - ./zk/kafka1/data:/var/lib/kafka/data
    depends_on:
      - zoo1
